/**
 * Unit tests for watermark filter
 */

import {
  detectWatermarks,
  removeWatermarks,
  validateNoWatermarks,
} from '../src/core/filters/watermarkFilter';

describe('Watermark Filter Tests', () => {
  describe('detectWatermarks', () => {
    it('should detect AI watermarks', () => {
      const text = 'This CV was generated by AI';
      const detections = detectWatermarks(text);
      expect(detections.length).toBeGreaterThan(0);
    });

    it('should not detect watermarks in clean text', () => {
      const text = 'Senior Frontend Developer with React experience';
      const detections = detectWatermarks(text);
      expect(detections.length).toBe(0);
    });
  });

  describe('removeWatermarks', () => {
    it('should remove AI watermarks from HTML', () => {
      const html = '<p>This CV was generated by AI</p><p>Clean content</p>';
      const cleaned = removeWatermarks(html);
      expect(cleaned).not.toContain('generated by AI');
      expect(cleaned).toContain('Clean content');
    });

    it('should clean up empty paragraphs', () => {
      const html = '<p></p><p>Content</p>';
      const cleaned = removeWatermarks(html);
      expect(cleaned).not.toContain('<p></p>');
    });
  });

  describe('validateNoWatermarks', () => {
    it('should return true for clean HTML', () => {
      const html = '<p>Clean content</p>';
      expect(validateNoWatermarks(html)).toBe(true);
    });

    it('should return false for HTML with watermarks', () => {
      const html = '<p>Generated by AI</p>';
      expect(validateNoWatermarks(html)).toBe(false);
    });
  });

  describe('custom keyword list (dependency injection)', () => {
    it('detects only the keywords it is given, not the defaults', () => {
      const text = 'Built with React and a proprietary internal framework';

      // "React" is not a default watermark keyword, so it is invisible
      // by default...
      expect(detectWatermarks(text)).toHaveLength(0);

      // ...but becomes detectable once passed in explicitly. This is
      // the behaviour the web app and worker rely on: they have no
      // config.yaml to read, so they must be able to supply their own
      // keyword list instead of only getting the CLI's defaults.
      const detections = detectWatermarks(text, ['React']);
      expect(detections).toEqual(['React']);
    });

    it('does not flag a default watermark keyword once it is excluded', () => {
      // "generated" is a default keyword, but this phrasing doesn't match
      // any of the sentence-level patterns either, so a keyword list that
      // excludes it should leave the text untouched.
      const text = 'This resume was generated for practice purposes';
      expect(detectWatermarks(text, ['assistant'])).toHaveLength(0);
    });
  });
});
