/**
 * Unit tests for watermark filter
 */

import {
  detectWatermarks,
  removeWatermarks,
  validateNoWatermarks,
} from '../src/filters/watermarkFilter';

describe('Watermark Filter Tests', () => {
  describe('detectWatermarks', () => {
    it('should detect AI watermarks', () => {
      const text = 'This CV was generated by AI';
      const detections = detectWatermarks(text);
      expect(detections.length).toBeGreaterThan(0);
    });

    it('should not detect watermarks in clean text', () => {
      const text = 'Senior Frontend Developer with React experience';
      const detections = detectWatermarks(text);
      expect(detections.length).toBe(0);
    });
  });

  describe('removeWatermarks', () => {
    it('should remove AI watermarks from HTML', () => {
      const html = '<p>This CV was generated by AI</p><p>Clean content</p>';
      const cleaned = removeWatermarks(html);
      expect(cleaned).not.toContain('generated by AI');
      expect(cleaned).toContain('Clean content');
    });

    it('should clean up empty paragraphs', () => {
      const html = '<p></p><p>Content</p>';
      const cleaned = removeWatermarks(html);
      expect(cleaned).not.toContain('<p></p>');
    });
  });

  describe('validateNoWatermarks', () => {
    it('should return true for clean HTML', () => {
      const html = '<p>Clean content</p>';
      expect(validateNoWatermarks(html)).toBe(true);
    });

    it('should return false for HTML with watermarks', () => {
      const html = '<p>Generated by AI</p>';
      expect(validateNoWatermarks(html)).toBe(false);
    });
  });
});
