/**
 * Unit tests for src/core/pipeline/postProcess.ts
 */

import fs from 'fs/promises';
import {
  stageRemoveWatermarks,
  rewriteTitleAndNormalize,
  validateFinalStructure,
  applyPostProcessing,
} from '../../src/core/pipeline/postProcess';

const BROKEN_HTML =
  '<html><head><link rel="stylesheet" href="shared.css"></head><body><main>no content div here</main></body></html>';

describe('stageRemoveWatermarks', () => {
  it('removes watermark phrasing and keeps a valid layout warning-free', () => {
    const html =
      '<html><head><link rel="stylesheet" href="shared.css"></head><body>' +
      '<div class="content"><p>This CV was generated by AI</p><p>Clean line</p></div>' +
      '</body></html>';
    const result = stageRemoveWatermarks(html);

    expect(result.html).not.toContain('generated by AI');
    expect(result.html).toContain('Clean line');
    expect(result.structureWarnings).toHaveLength(0);
  });

  it('always removes watermarks regardless of checkWatermarks, which only gates detection', () => {
    const html = '<div class="content"><p>This CV was generated by AI</p></div>';
    const result = stageRemoveWatermarks(html, { checkWatermarks: false });

    expect(result.watermarksChecked).toBe(false);
    expect(result.watermarkDetections).toHaveLength(0);
    expect(result.html).not.toContain('generated by AI');
  });

  it('reports zero detections after removal, since detection reuses the same keyword list', () => {
    // removeWatermarks and detectWatermarks share the same pattern list
    // here, so anything the detector would flag was already stripped by
    // removal one line above it - this mirrors the CLI's original
    // behaviour exactly (the check is a self-verification step, and in
    // practice it should never find anything left to report).
    const html = '<div class="content"><p>This CV was generated by AI</p></div>';
    const result = stageRemoveWatermarks(html);

    expect(result.watermarksChecked).toBe(true);
    expect(result.watermarkDetections).toHaveLength(0);
  });

  it('turns a structural failure into a warning instead of throwing', () => {
    expect(() => stageRemoveWatermarks(BROKEN_HTML)).not.toThrow();

    const result = stageRemoveWatermarks(BROKEN_HTML);
    expect(result.structureWarnings.length).toBeGreaterThan(0);
    expect(result.structureWarnings[0]).toMatch(/content/i);
  });
});

describe('rewriteTitleAndNormalize', () => {
  it('rewrites the header title and normalizes the stylesheet href, without validating', () => {
    const html =
      '<html><head><link rel="stylesheet" href="../original/shared.css"></head>' +
      '<body><div class="content"><p>Miguel Rivero López</p><p>Old Title</p><p>contact</p></div></body></html>';

    const updated = rewriteTitleAndNormalize(html, {
      jobTitle: 'senior-frontend-developer',
      candidateName: 'Miguel Rivero López',
    });

    expect(updated).toContain('<p>Senior Frontend Developer</p>');
    expect(updated).toContain('href="shared.css"');

    // Deliberately does not validate - even a broken layout comes back
    // as HTML, so the PDF-input reflow step in the CLI can still run on
    // it before the final check happens.
    expect(() =>
      rewriteTitleAndNormalize(BROKEN_HTML, { jobTitle: 'x', candidateName: 'x' })
    ).not.toThrow();
  });
});

describe('validateFinalStructure', () => {
  it('returns no warnings for a valid layout', async () => {
    const html = await fs.readFile('original/MR_cv_base.html', 'utf-8');
    expect(validateFinalStructure(html)).toHaveLength(0);
  });

  it('returns a warning instead of throwing for a broken layout', () => {
    const warnings = validateFinalStructure(BROKEN_HTML);
    expect(warnings.length).toBeGreaterThan(0);
  });
});

describe('applyPostProcessing', () => {
  it('runs the full pipeline against the real base CV with no warnings', async () => {
    const baseHtml = await fs.readFile('original/MR_cv_base.html', 'utf-8');

    const result = applyPostProcessing(baseHtml, {
      jobTitle: 'senior-frontend-developer',
      candidateName: 'Miguel Rivero López',
    });

    expect(result.structureWarnings).toHaveLength(0);
    expect(result.html).toContain('<p>Senior Frontend Developer</p>');
  });

  it('never throws, even when the input HTML has no .content root', () => {
    expect(() =>
      applyPostProcessing(BROKEN_HTML, {
        jobTitle: 'developer',
        candidateName: 'Miguel Rivero López',
      })
    ).not.toThrow();

    const result = applyPostProcessing(BROKEN_HTML, {
      jobTitle: 'developer',
      candidateName: 'Miguel Rivero López',
    });

    // Both the post-removal check and the final check fail on HTML that
    // never had a .content root to begin with.
    expect(result.structureWarnings.length).toBeGreaterThanOrEqual(1);
  });
});
